sudo: false
language: node_js
branches:
  only:
    - master
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - ~/.nuxt
    - node_modules
before_script:
  - npm install -g npm@latest
install:
  - npm install
  - npm run setup:default
script:
  - npm run build
